spring:
  datasource:
    url: jdbc:mysql://localhost:3306/efps_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 194044
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true